#!/bin/bash
cmake -B build -DCMAKE_INSTALL_PREFIX=/usr/local -Dtaktile_ENABLE_TESTS=OFF -Dtaktile_BUILD_EXAMPLES=OFF -S . -B build
cmake --build build
cmake --install build --prefix ./package-root
cpack --config build/CPackConfig.cmake
